version: "3.3"
services:
  # Frontend Application.
  notedown_fe:
    build:
      context: ..
      dockerfile: ./deployment/notedown_fe.dockerfile
    command: ["serve", "-l", "tcp://0.0.0.0:3000", "&"]
    container_name: notedown_fe
    environment:
      - NODE_ENV=production
    depends_on:
      - notedown_db
      - notedown_api
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # Backend API
  notedown_api:
    build:
      context: ..
      dockerfile: ./deployment/notedown_api.dockerfile
    container_name: notedown_api
    environment:
      NOTEDOWN_DB_URL: "postgresql://notedown_db_user:${NOTEDOWN_DB_PASSWORD-notedown}@notedown_db:5432/notedown_db"
    depends_on:
      - notedown_db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # Database
  notedown_db:
    image: postgres
    restart: always
    container_name: notedown_db
    environment:
      POSTGRES_PASSWORD: ${NOTEDOWN_DB_PASSWORD-notedown}
      POSTGRES_USER: notedown_db_user
      POSTGRES_DB: notedown_db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    expose:
      - 5432

  notedown_app:
    build:
      context: ..
      dockerfile: ./deployment/notedown_app.dockerfile
    container_name: notedown_app
    environment:
      VIRTUAL_HOST: notedown.juanbiondi.com,www.notedown.juanbiondi.com
    depends_on:
      - notedown_db
      - notedown_fe
      - notedown_api

networks:
  default:
    external:
      name: nginx-proxy
